-   hosts: localhost
    vars:
        # Setup config
        shinken_repokey: # Insert repokey if required
        shinken_repourl: # Repository URL that contains shinken and openio_import if needed

        # Internal config: add hosts, services or contacts here
        shinken_hosts:
            - { host_name: 'localhost', hostgroups: [ 'all' ] }
        shinken_services:
            - { service_description: 'ping_test', check_command: 'check_ping', hostgroup_name: ['all'] }
            - { service_description: 'port_7776_test', check_command: 'check_tcp!7776', hostgroup_name: ['all'] }
        shinken_contacts:
            -   contact_name: 'admin'
                email: 'admin@example.com'
                password: 'secret'
                notificationways: 'email'
                is_admin: 1
                expert: 1

        # Mod enabling: uncomment mods to enable them
        shinken_mods:
            arbiter:
                # - openio_import
                # - named-pipe
            broker:
                # - influxdb
            misc:
                # - forward_nagios
            scheduler:
                # - RedisRetention

        # Mod config
        shinken_openio_import:
            host: 127.0.0.1
            port: 8002
            key: secret
        shinken_influxdb:
            host: 127.0.0.1
            port: 8086
            user: root
            password: secret
            db: shinken
        shinken_forward_nagios:
            identity: web-checker
            password: secretz
            server: localhost
            tls_ciphers: PSK-AES256-CBC-SHA
            delay: 2
            port: 5668
            timeout: 10
        shinken_named_pipe:
            command_file: /var/lib/nagios.cmd
        shinken_redis_retention:
            server: 127.0.0.1

    roles:
        - { role: ansible-shinken }
