---

- name: Alias Distro (CentOS)
  when: ansible_distribution == 'CentOS'
  set_fact:
      shinken_distro: "{{ansible_distribution}}-{{ansible_distribution_major_version}}"

- name: Alias Distro (Ubuntu)
  when: ansible_distribution == 'Ubuntu'
  set_fact:
      shinken_distro: "{{ansible_distribution}}-{{ansible_distribution_version}}"

- name: Compatibility check
  when: "shinken_distro not in shinken_supported_distros"
  fail:
    msg: "shinken_distro not in supported distros: {{shinken_supported_distros | join(', ')}}"

- name: Gather OS specific variables
  include_vars: "{{ ansible_os_family|lower }}.yml"

- name: Install EPEL On CentOS
  when: ansible_distribution|lower in ('centos',)
  yum:
      name: epel-release
      state: present

- name: Install monitoring plugins
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - "{{ shinken_monitoring_plugins }}"

- include: install/{{ansible_distribution|lower}}.yml
