---
- include: install.yml

- include: configure.yml

- include: mods/influxdb.yml
  when: "shinken_mods['broker'] and ('influxdb' in shinken_mods['broker'])"

- include: mods/nagios_forward.yml
  when: "shinken_mods['misc'] and ('forward_nagios' in shinken_mods['misc'])"

- include: mods/openio_import.yml
  when: "shinken_mods['arbiter'] and ('openio_import' in shinken_mods['arbiter'])"

- include: mods/retention_redis.yml
  when: "shinken_mods['scheduler'] and ('RedisRetention' in shinken_mods['scheduler'])"

- include: mods/named_pipe.yml
  when: "shinken_mods['arbiter'] and ('named-pipe' in shinken_mods['arbiter'])"

- include: systemd.yml
  when: "ansible_service_mgr == 'systemd'"

- include: postinstall.yml
