---
- include: install.yml

- include: configure.yml

- include: mods/influxdb.yml
  when: "mods['broker'] and ('influxdb' in mods['broker'])"

- include: mods/nagios_forward.yml
  when: "mods['misc'] and ('forward_nagios' in mods['misc'])"

- include: mods/openio_import.yml
  when: "mods['arbiter'] and ('openio_import' in mods['arbiter'])"

- include: mods/retention_redis.yml
  when: "mods['scheduler'] and ('RedisRetention' in mods['scheduler'])"

- include: mods/named_pipe.yml
  when: "mods['arbiter'] and ('named-pipe' in mods['arbiter'])"

- include: postinstall.yml
