---

- name: Update services - Arbiter
  lineinfile:
    dest: "{{ shinken_config_dir }}/arbiters/arbiter-master.cfg"
    state: present
    regexp: '.*[^#] modules.*'
    line: "    modules {{ shinken_mods['arbiter'] | join(',') if shinken_mods['arbiter'] else ''  }}"

- name: Update services - Broker
  lineinfile:
    dest: "{{ shinken_config_dir }}/brokers/broker-master.cfg"
    state: present
    regexp: '.*[^#] modules.*'
    line: "    modules {{ shinken_mods['broker'] | join(',') if shinken_mods['broker'] else '' }}"

- name: Update services - Scheduler
  lineinfile:
    dest: "{{ shinken_config_dir }}/schedulers/scheduler-master.cfg"
    state: present
    regexp: '.*[^#] modules.*'
    line: "    modules {{ shinken_mods['scheduler'] | join(',') if shinken_mods['scheduler'] else '' }}"

- name: Restart Shinken
  debug:
    msg: "Setup completed"
  changed_when: True
  notify:
    - validate config
    - restart shinken
    - restart shinken systemd

- name: Display warning when using docker + CentOS7
  when: ansible_virtualization_type == 'docker' and shinken_distro == 'CentOS-7'
  debug:
      msg: |
        It looks like you are using docker on CentOS 7, which doesn't have systemd access nor an installed 'initscripts'
        You will need to start shinken services manually one by one.
