---
- name: Validate configuration
  # Service command can't be used as it doesn't support 'check'
  command: service shinken check

- name: restart shinken systemd
  when: "ansible_service_mgr == 'systemd'"
  command: systemctl restart shinken.target

- name: restart shinken
  when: "ansible_service_mgr != 'systemd'"
  service: name=shinken state=restarted
